### ISSUE TITLE
Use yarn install with --prefer-offline and --pure-lockfile ?

### ISSUE THREAD

**Issue by christophehurpeau** [frontsideair/yarnhook#24]
`--prefer-offline`:
 > use network only if dependencies are not available in local cache

Make yarn install faster when switching branches

`--pure-lockfile`
> don't generate a lockfile

yarnhook should not change yarn lockfile, and I don't think we should use `frozen-lockfile` which could fail when the lockfile is not synced with package.json yet.

**Comment by frontsideair** [comment]
Both of these suggestions make a lot of sense to me, so thanks! 👍 I think I can do it this weekend or leave it to you if you'd rather do it.

I'd also appreciate investigating similar sane defaults for other supported package managers if you decide you wanna do it.

**Comment by christophehurpeau** [comment]
npm: 
`--prefer-offline` (https://blog.npmjs.org/post/161081169345/v500)

> A new --prefer-offline option will make npm skip any conditional requests (304 checks) for stale cache data, and only hit the network if something is missing from the cache.

`--no-audit` maybe ? https://docs.npmjs.com/cli/install 

> The --no-audit argument can be used to disable sending of audit reports to the configured registries. See npm-audit for details on what is sent.

**Comment by frontsideair** [comment]
I think these options make more sense than the alternatives, and I agree that the package managers should offer more options. It may make sense to open issues to address these problems.
