### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by frontsideair** [frontsideair/yarnhook#7]
Something like this
![crochet-hook-yarn-brooch-purple-sparkle](https://user-images.githubusercontent.com/868283/34412343-c1baa052-ebed-11e7-9d5e-04ccc9df460c.jpg)

**Comment by AnilKilic** [comment]
![yarnhook](https://user-images.githubusercontent.com/2311397/34439458-34991910-ecbf-11e7-9280-a4e317671921.png)

Font: PT Sans
Easily editable with Adobe Illustrator.
[yarnhook-logo.ai.zip](https://github.com/frontsideair/yarnhook/files/1593291/yarnhook-logo.ai.zip)

**Comment by frontsideair** [comment]
Wow, that's awesome! I have no objections to this, will add it asap. Thanks a lot!!! 🙏

**Comment by frontsideair** [comment]
It's merged, thanks again! 🎉

**Comment by anilkilic** [comment]
Glad to see it alive, don't hesitate to contact me if you want any revisions or else.
