### ISSUE TITLE
Adding pnpm support

### ISSUE THREAD

**Issue by zkochan** [frontsideair/yarnhook#9]
Adding [pnpm](https://github.com/pnpm/pnpm) support should be really easy.

I see currently this tool checks for a lockfile to decide what pm should be used for installation. pnpm has its own lockfile called `shrinkwrap.yaml`.

Alternatively, [which-pm](https://github.com/zkochan/which-pm) can be used, which will correctly identify the pm even when installing was done w/o a lockfile creation

**Comment by frontsideair** [comment]
Both ideas sound great, but let's handle them separately. Would you like to implement pnpm support? I can do that if you'd not prefer to. A separate issue would be great for adding which-pm dependency, which I have briefly checked yet, but looks solid.

**Comment by zkochan** [comment]
great, I'll create a PR
